spring:
  profiles:
    active: local

---

spring:
  config:
    activate:
      on-profile: local

  session:
    store-type: jdbc
    jdbc.initialize-schema: always

#  datasource:
#    url: jdbc:mysql://${MYSQL_HOST}:${MYSQL_PORT}/${MYSQL_DATABASE}?useSSL=false&serverTimezone=UTC&useLegacyDatetimeCode=false&allowPublicKeyRetrieval=true
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    username: ${MYSQL_USERNAME}
#    password: ${MYSQL_PASSWORD}

  datasource:
    url: ${SPRING_DATASOURCE_URL}
    driver-class-name: ${SPRING_DATASOURCE_DRIVER}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}


  jpa:
    hibernate:
      ddl-auto: none #create update none
    properties:
      hibernate:
        default_batch_fetch_size: 100
        #show-sql: true
        format_sql: true
        dialect: org.hibernate.dialect.MySQLDialect



logging.level:
  org.hibernate.SQL: debug
  #org.hibernate.orm.jdbc.bind: trace
server:
  port: 8080
  servlet:
    context-path:
